version: '3'
services:

  mysql:
    image: mysql
    environment:
    - MYSQL_USER=teste
    - MYSQL_PASSWORD=@Abc123
    - MYSQL_DATABASE=teste
    - MYSQL_ROOT_PASSWORD=#!aBC123
    volumes:
    - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
    - 8080:80
    
volumes:
  mysql_data: {}